/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bEngine;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainDriverTest {
    @Test public void testSomeLibraryMethod() {
        MainDriver classUnderTest = new MainDriver();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
