/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bEngine;

import com.google.gson.Gson;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class MainDriver extends Application{
	
	public static void main(String[] args) {
		/*Gson gson = new Gson();
		String test = gson.toJson(new Feeder(20, "CLIF", "Cliff", 1));
		
		System.out.println(test);
		
		Feeder thing = gson.fromJson(test, Feeder.class);
		
		System.out.println(thing.getBattery());
		thing.setBattery(40);
		System.out.println(thing.getBattery());//*/
		launch(args);
	}

	public void start(Stage stage) {
		//Start every JavaFx program with these 5 lines of code:
		Group root = new Group(); //a Group is a collection of shapes to put on the screen.
		Scene scene = new Scene(root, 800, 600); // 800 by 600 pixel screen
		stage.setScene(scene);
		stage.setTitle("Hello everyone");
		stage.show(); //shows the "actual" window.

	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
