/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bEngine;

import com.google.gson.Gson;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.RowConstraints;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class MainDriver extends Application{
	
	public static void main(String[] args) {
		/*Gson gson = new Gson();
		String test = gson.toJson(new Feeder(20, "CLIF", "Cliff", 1));
		
		System.out.println(test);
		
		Feeder thing = gson.fromJson(test, Feeder.class);
		
		System.out.println(thing.getBattery());
		thing.setBattery(40);
		System.out.println(thing.getBattery());//*/
		launch(args);
	}

	public void start(Stage stage) {
		/* START SELECTION GROUP */
		Group selectionRoot = new Group(); //a Group is a collection of shapes to put on the screen.
		Scene selectionScene = new Scene(selectionRoot); // 800 by 600 pixel screen
		stage.setTitle("bEngine");
		
		Button feederButton = new Button("Feeder");
		Button birdButton = new Button("Bird");
		Button visitButton = new Button("Visit");
		Button saveButton = new Button("Save");
		Button exitButton = new Button("Exit");
		
		VBox firstCol = new VBox(10);
		HBox selectionAdminRow = new HBox(10);
		firstCol.getChildren().addAll(feederButton, birdButton, visitButton);
		selectionAdminRow.getChildren().addAll(saveButton, exitButton);
		GridPane.setRowIndex(firstCol, 1);
		GridPane.setColumnIndex(firstCol, 1);
		GridPane selectionGrid = new GridPane();
		for(int i = 0; i < 3; i++) {
			selectionGrid.getColumnConstraints().add(new ColumnConstraints(100));
			selectionGrid.getRowConstraints().add(new RowConstraints(100));
		}
		selectionGrid.setHgap(10);
		selectionGrid.getChildren().addAll(firstCol);
		
		BorderPane.setAlignment(selectionAdminRow, Pos.CENTER_RIGHT);
		BorderPane.setMargin(selectionAdminRow, new Insets(10, 10, 10, 100));
		BorderPane selectionBorderPane = new BorderPane();
		selectionBorderPane.setCenter(selectionGrid);
		selectionBorderPane.setBottom(selectionAdminRow);

		selectionRoot.getChildren().add(selectionBorderPane);
		/* END SELECTION GROUP */
		/* START FEEDER GROUP */
		Group feederRoot = new Group();
		Scene feederScene = new Scene(feederRoot, 800, 600);
		/* END FEEDER GROUP */
		/* START BIRD GROUP */
		/* END BIRD GROUP */
		/* START VISIT GROUP */
		/* END VISIT GROUP */
		stage.setScene(selectionScene);
		stage.show(); //shows the "actual" window.

	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
